name: Kotlin_build  # <-- changed name

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Install Kotlin compiler
      - name: Install Kotlin
        run: sudo snap install --classic kotlin

      # Step 4: Compile all Kotlin files (root + src)
      - name: Compile Kotlin
        run: kotlinc *.kt src/*.kt -include-runtime -d Main.jar

      # Step 5: Run Kotlin program
      - name: Run Kotlin program
        run: java -jar Main.jar
