name: Kotlin_build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine branch for setup
        id: branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH=main" >> $GITHUB_ENV
          fi

      - name: Setup repository branch
        run: Scripts/SetUpRepo.bat
        shell: cmd
        env:
          BRANCH_NAME: ${{ env.BRANCH }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build project
        run: ./gradlew build

      - name: Run application
        run: ./gradlew run
